language: node_js
node_js:
  - "8.9"

branches:
  only:
    - master

script:
  - ng build --prod
  - npm install sonar-scanner
- sonar-scanner -Dsonar.projectKey=GalgobebersonFlanderson_angular-smelly-code-test -Dsonar.organization=galgobebersonflanderson-github -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN